name: Deploy Bicep

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az group create --name "omerfarukyilmaz2" --location "eastus2"
          az deployment group create --resource-group "omerfarukyilmaz2" --template-file main.bicep
